version: '3'
services:
  java-app:
    image: 137.184.78.100:8083/java-app:1.0
    ports:
      - 8080:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
    container_name: app
    depends_on:
      - mysql
  mysql:
    image: mysql:8.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    links:
      - "mysql:db"
    container_name: phpmyadmin
    depends_on:
     - mysql
volumes:
  mysql-data:
    driver: local